{{- if .Values.minio.enabled -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "minio-keys") }}
{{- $password := "" }}
{{- $username := "" }}
{{- if $existingSecret }}
  {{- $password = $existingSecret.data.secretKey | b64dec }}
  {{- $username = $existingSecret.data.accessKey | b64dec }}
{{- else if not .Values.dryRun -}}
  {{- fail "Existing secret 'minio-keys' not found!" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-env
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ $username }}
    export MINIO_ROOT_PASSWORD={{ $password }}
{{- end -}}
