{{- if and .Values.openedx.traefik.enabled .Values.openedx.lms.enabled -}}
{{- $host := .Values.openedx.lms.host }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: favicon-rewrite
  annotations:
    {{- include "openedx.annotations" . | nindent 4 }}
spec:
  replacePathRegex:
    regex: ^/favicon\.ico$
    replacement: /theming/asset/images/favicon.ico
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: profile-upload-limit
  annotations:
    {{- include "openedx.annotations" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.openedx.lms.ingress.profileUpload.maxRequestBodyBytes | default 1048576 }}  # 1MB
    memRequestBodyBytes: {{ .Values.openedx.lms.ingress.profileUpload.memRequestBodyBytes | default 1048576 }}
    maxResponseBodyBytes: {{ .Values.openedx.lms.ingress.profileUpload.maxResponseBodyBytes | default 0 }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: default-body-limit
  annotations:
    {{- include "openedx.annotations" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: {{ .Values.openedx.lms.ingress.default.maxRequestBodyBytes | default 4194304 }}  # 4MB
    memRequestBodyBytes: {{ .Values.openedx.lms.ingress.default.memRequestBodyBytes | default 4194304 }}
    maxResponseBodyBytes: {{ .Values.openedx.lms.ingress.default.maxResponseBodyBytes | default 0 }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lms-ingressroute
  annotations:
    {{- include "openedx.annotations" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
{{- range .Values.openedx.lms.localRoutes }}
    - match: Host(`{{ .host | default $host }}`) && PathPrefix(`{{ .path }}`)
      kind: Rule
      middlewares:
        - name: add-headers
        - name: compress-gzip
        - name: cors-allowed-origins
{{- if .suppressPath }}
        - name: stripprefix-lms-{{ .name }}
{{- end }}
      services:
        - name: external-lms-{{ .name }}
          port: {{ .port }}
{{- end }}
    - match: Host(`{{ $host }}`) && PathPrefix(`/api/profile_images`)
      kind: Rule
      middlewares:
      - name: favicon-rewrite
      - name: profile-upload-limit
      services:
      - name: {{ .Values.openedx.lms.service.name | default "lms" }}
        port: {{ .Values.openedx.lms.service.port | default 8000 }}
    - match: Host(`{{ $host }}`)
      kind: Rule
      middlewares:
      - name: favicon-rewrite
      - name: default-body-limit
      - name: add-headers
      - name: compress-gzip
      - name: cors-allowed-origins
      services:
      - name: {{ .Values.openedx.lms.service.name | default "lms" }}
        port: {{ .Values.openedx.lms.service.port | default 8000 }}
  tls:
    {{- include "openedx.ingressroute.tlsname" (dict "component" "lms" "root" .) | nindent 4 }}
---
{{- include "openedx.ingressroute.tlscertificate" (dict "component" "lms" "root" .) }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lms-ingressroute-preview
  annotations:
    {{- include "openedx.annotations" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ .Values.openedx.preview.host }}`) && PathPrefix(`/api/profile_images`)
    kind: Rule
    middlewares:
    - name: favicon-rewrite
    - name: profile-upload-limit
    services:
    - name: {{ .Values.openedx.lms.service.name | default "lms" }}
      port: {{ .Values.openedx.lms.service.port | default 8000 }}
  - match: Host(`{{ .Values.openedx.preview.host }}`)
    kind: Rule
    middlewares:
    - name: favicon-rewrite
    - name: default-body-limit
    - name: add-headers
    - name: compress-gzip
    - name: cors-allowed-origins
    services:
    - name: {{ .Values.openedx.lms.service.name | default "lms" }}
      port: {{ .Values.openedx.lms.service.port | default 8000 }}
  tls:
    {{- include "openedx.ingressroute.tlsname" (dict "component" "preview" "root" .) | nindent 4 }}
---
{{- include "openedx.ingressroute.tlscertificate" (dict "component" "preview" "root" .) }}

{{- end -}}
