{{- if and .Values.minio.enabled .Values.minio.extendedOperator.user -}}
apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: {{ .Values.minio.extendedOperator.user.name }}-buckets-policy
spec:
  name: {{ .Values.minio.extendedOperator.user.name }}-buckets-policy
  statement:

    - effect: "Allow"
      action:
        - "s3:AbortMultipartUpload"
        - "s3:DeleteObject"
        - "s3:ListMultipartUploadParts"
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:GetBucketLocation"
      resource:
{{- range .Values.minio.extendedOperator.buckets }}
        - "arn:aws:s3:::{{ .name }}/*"
{{- end }}
    - effect: "Allow"
      action:
        - "s3:GetBucketLocation"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
      resource:
{{- range .Values.minio.extendedOperator.buckets }}
        - "arn:aws:s3:::{{ .name }}"
{{- end }}

  tenantRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.minio.tenant.name }}
  version: "2012-10-17"
{{- end -}}
