{{- if and .Values.ferretdb.backups.enabled .Values.ferretdb.backups.barmanObjectName .Values.ferretdb.cluster.walArchive.enabled -}}
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: {{ .Values.ferretdb.backups.barmanObjectName | default "minio-store-documentdb" }}
  annotations:
    {{- include "openedxinfra.annotations" . | nindent 4 }}
  labels:
    {{- include "openedxinfra.componentLabels" (dict "component" "ferretdb" "root" .) | nindent 4 }}
spec:
  retentionPolicy: {{ .Values.ferretdb.backups.retention | default "7d" | quote }}
  configuration:
    destinationPath: s3://{{ .Values.ferretdb.backups.destinationPath | default "documentdb-backups" }}
    endpointURL: {{ .Values.ferretdb.backups.endpointURL | default "http://minio.backups.svc.cluster.local" }}
    s3Credentials:
      accessKeyId:
        name: {{ .Values.ferretdb.backups.s3Credentials.accessKeyId.name | default "minio-backups-secret" }}
        key: {{ .Values.ferretdb.backups.s3Credentials.accessKeyId.key | default "user" }}
      secretAccessKey:
        name: {{ .Values.ferretdb.backups.s3Credentials.secretAccessKey.name | default "minio-backups-secret" }}
        key: {{ .Values.ferretdb.backups.s3Credentials.secretAccessKey.key | default "password" }}
    wal:
      # bzip2;gzip;lz4;snappy;xz;zstd
      compression: {{ .Values.ferretdb.backups.walCompression | default "bzip2" }}
    data:
      # bzip2;gzip;snappy
      compression: {{ .Values.ferretdb.backups.dataCompression | default "bzip2" }}
{{- end -}}
