{{- if and .Values.openedx.isDev .Values.openedx.dev.files.lbIP .Values.openedx.dev.backups.lbIP -}}
{{- $domains := (list .Values.minio.ingress.api.host ) | uniq -}}
{{- $backupsDomains := (list .Values.db.backups.host .Values.ferretdb.backups.host) | uniq -}}
{{- $allDomains := (concat $domains $backupsDomains) | uniq -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom # this is the name of the configmap you can overwrite with your changes
  namespace: kube-system
data:
    files.server: |
          {{ join " " $allDomains }} {
              hosts {
                  {{ .Values.openedx.dev.files.lbIP }} {{ join " " $domains }}
                  {{ .Values.openedx.dev.backups.lbIP }} {{ join " " $backupsDomains }}
                  fallthrough
              }
          }
{{- end -}}
