{{- if .Values.openedx.certManager.enabled -}}
{{- range $issuer := .Values.openedx.certManager.issuers }}
{{- if and $issuer.name $issuer.server $issuer.email $issuer.privateKeySecretRef -}}
---
apiVersion: cert-manager.io/v1
kind: {{ $issuer.kind | default "Issuer" }}
metadata:
  name: {{ $issuer.name }}
spec:
  acme:
    server: {{ $issuer.server }}
    email: {{ $issuer.email }}
    privateKeySecretRef:
      name: {{ $issuer.privateKeySecretRef }}
    solvers:
    - http01:
        ingress:
          class: traefik
{{- end -}}
{{- end -}}
{{- end -}}
